README.md

Signed-off-by: Scott Rigby <scott@r6by.com>

Update workflow example

---

action.yml

Updates action icon to box (will be blue)
See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#icon

Update actions icon

---

action.yml

prep for marketplace
Signed-off-by: Scott Rigby <scott@r6by.com>

Change action name

---

README.md
action.yml
kind.sh

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/helm/kind-action/9)

Upgrade to kind v0.6.1

---

kind.sh

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/helm/kind-action/11)

Upgrade kubectl

---

README.md

Signed-off-by: Reinhard Naegele <unguiculus@gmail.com>

Update readme for v1.0.0-rc.1

---

README.md
kind.sh

Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

Update kind and kubectl

---

README.md

Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

Update readme for v1.0.0 release

---

README.md

Signed-off-by: Reinhard Nägele <unguiculus@gmail.com>

Update readme for v1.1.0

---

kind.sh

This PR just bumps the tool versions used in the action to the latest releases upstream.

Bump tool versions

---

.github/workflows/test.yaml
README.md

/assign @unguiculus @scottrigby

Update default branch reference from master to main

---

README.md
action.yml
kind.sh

- update kind to 0.11.1
- kubectl to 1.20.8

defaults kind to 0.11.1 and kubectl to 1.20.8

---

.github/dependabot.yml
.github/workflows/test.yaml
README.md
action.yml
kind.sh

- Update kind to v0.12.0 and default k8s version to v1.21.10
- add dependabot

Update kind to v0.12.0 and default k8s version to v1.21.10

---

.github/workflows/test.yaml
README.md
action.yml
kind.sh

update kind to v0.16.0

---

kind.sh

Fixing issue #68 - kind.sh: line 60: dpkg: command not found

---

kind.sh

Signed-off-by: Jorge Turrado <jorge_turrado@hotmail.es>
Fixes https://github.com/helm/kind-action/issues/70

fix: add aarch64 for uname case

---

README.md

I've updated the version in the example workflow.
Thanks!

Update version in the example workflow

---

.github/workflows/test.yaml
README.md
action.yml
kind.sh

- bump kind to use v0.17.0 and kubectl v1.25.5

bump kind to use v0.17.0 and kubectl v1.25.5

---

.github/workflows/test.yaml
README.md
action.yml
kind.sh

- update kind to v0.18.0 and kubectl to v1.26.4
Fixes: https://github.com/helm/kind-action/issues/75

update kind to v0.18.0 and kubectl to v1.26.4

---

README.md
action.yml
kind.sh

- https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0

default action to use kind release v0.19.0

---

.github/workflows/test.yaml

related to https://github.com/helm/kind-action/issues/101

add wait test
